BEGIN;

CREATE TABLE IF NOT EXISTS user_status (
    user_id   INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    online    BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
