BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS extra_info TEXT,
    ADD COLUMN IF NOT EXISTS avatar_url TEXT,
    ADD COLUMN IF NOT EXISTS avatar_path TEXT,
    ADD COLUMN IF NOT EXISTS avatar_original_path TEXT,
    ADD COLUMN IF NOT EXISTS avatar_crop_x NUMERIC,
    ADD COLUMN IF NOT EXISTS avatar_crop_y NUMERIC,
    ADD COLUMN IF NOT EXISTS avatar_crop_scale NUMERIC,
    ADD COLUMN IF NOT EXISTS avatar_crop_size NUMERIC,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMIT;
