server:
  port: 4000

database:
  url: "postgres://postgres:1234@localhost:5432/turcompany?sslmode=disable"

email:
  smtp_host: "smtp.mail.ru"
  smtp_port: 465
  smtp_user: "placeholder"
  smtp_password: "placeholder"
  from_email: "placeholder"

files:
  root_dir: "./files"

mobizon:
  api_key: "dry-run"   # для тестов: "dry-run" => в сеть не ходим
  sender_id: ""        # если есть утверждённый Sender ID — укажи
  dry_run: false       # true = только логируем, без реального запроса
