server:
  port: 4000
  tz: "Asia/Almaty"

database:
  url: "postgres://kubcrm_user:kub_srmuserpassword!@127.0.0.1:5432/kubcrm?sslmode=disable"

email:
  smtp_host: "smtp.mail.ru"
  smtp_port: 587            # если используешь STARTTLS; для 465 нужен SMTPS в коде
  smtp_user: "noreply.kub@mail.ru"
  smtp_password: "NfnhWZEdBvlmQH9tpLl1"
  from_email: "noreply.kub@mail.ru"

files:
  root_dir: "./files"

templates:
  docx_dir: "assets/templates/docx"
  xlsx_dir: "assets/templates/xlsx"
  txt_dir: "assets/templates/txt"

libreoffice:
  enable: false
  binary: "libreoffice"

mobizon:
  api_key: "kzfaad0a91a4b498db593b78414dfdaa2c213b8b8996afa325a223543481efeb11dd11"   # для тестов: "dry-run" => в сеть не ходим
  sender_id: ""        # если есть утверждённый Sender ID — укажи
  dry_run: false       # true = только логируем, без реального запроса

telegram:
  enable: true
  bot_token: "8330092819:AAFWk-8GRKJwKsWDNv4Eo6oc1JU3ekgKX3E"     # токен бота BotFather
  webhook_url: "https://siegeable-elene-gooier.ngrok-free.dev/integrations/telegram/webhook"

frontend:
  host: "https://frontend.example.com"
